In [120]:
import pandas as pd

In [121]:
df = pd.read_csv("ecommerce_sales_data.csv")
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

In [123]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [157]:
df.duplicated().sum()

np.int64(3)

In [125]:
df.columns = df.columns.str.strip()

In [126]:
df.columns.tolist()

['ID',
 'Customer_Name',
 'Order_ID',
 'Order_Date',
 'Product',
 'Category',
 'Quantity',
 'Price',
 'Payment_Method',
 'Status',
 'Total']

In [127]:
print(df["Category"].unique())

['Home' 'Electronics' 'Sports' 'Books' 'sports' 'Clothing' 'electronic'
 'ELECTRONICS' 'electronics' nan]

In [128]:
print(df["Payment_Method"].unique())

['Cash on Delivery' 'PayPal' 'Bank Transfer' 'Credit Card']

In [129]:
print(df["Status"].unique())

['Shipped' 'Processing' 'Delivered' 'Cancelled' 'Returned']

In [130]:
df["Product"].unique()

array(['Blender', 'Smartphone', 'Tennis Racket', 'Science', 'Biography',
       'Basketball', 'Comics', 'Shoes', 'Fiction', 'Microwave',
       'Yoga Mat', 'Vacuum', 'Lamp', 'T-shirt', 'Smartwatch',
       'Headphones', 'Football', 'Laptop', 'Jacket', 'shoes', 'Jeans'],
      dtype=object)

## Standardize Categories

In [131]:
df["Category"]=df["Category"].str.strip().str.title()

In [132]:
df["Category"].unique()

array(['Home', 'Electronics', 'Sports', 'Books', 'Clothing', 'Electronic',
       nan], dtype=object)

## Handling missing values

In [133]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [134]:
df["Price"]=pd.to_numeric(df["Price"],errors = "coerce")

In [135]:
df["Price"].isnull().sum()

np.int64(9)

In [136]:
df["Price"]=df["Price"].fillna(
    df.groupby("Category")["Price"].transform("mean")
)

In [137]:
df.Price.isnull().sum()

np.int64(0)

In [138]:
df.isnull().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           0
Quantity           5
Price              0
Payment_Method     0
Status             0
Total             14
dtype: int64

In [139]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [140]:
df["Total"]=df["Total"].fillna(df["Quantity"]*df["Price"])

In [141]:
df.isnull().sum()

ID                0
Customer_Name     0
Order_ID          0
Order_Date        0
Product           0
Category          0
Quantity          0
Price             0
Payment_Method    0
Status            0
Total             0
dtype: int64

## Remove duplicate rows

In [156]:
df.duplicated().sum()

np.int64(3)

In [143]:
df["Total"] = df["Quantity"] * df["Price"]

In [144]:
df[df.duplicated()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1.0,111.36,Credit Card,Processing,111.36
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5.0,645.26,Credit Card,Shipped,3226.30
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,Electronic,2.0,705.42,Bank Transfer,Processing,1410.84

In [145]:
df.drop_duplicates().copy()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,38.000000,Cash on Delivery,Shipped,114.000000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2.0,468.885333,PayPal,Processing,937.770667
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1.0,389.050000,PayPal,Delivered,389.050000
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5.0,233.920000,PayPal,Processing,1169.600000
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1.0,552.510000,Cash on Delivery,Processing,552.510000
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3.0,122.060000,Cash on Delivery,Cancelled,366.180000
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,3.0,978.630000,Bank Transfer,Processing,2935.890000
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5.0,587.680000,PayPal,Returned,2938.400000
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1.0,600.290000,Cash on Delivery,Processing,600.290000
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5.0,168.340000,Credit Card,Shipped,841.700000
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,Sports,5.0,498.081333,Cash on Delivery,Cancelled,2490.406667
11,111,Customer_111,ORD-72349,10/22/2025,Comics,Books,2.0,865.770000,Credit Card,Returned,1731.540000
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,Clothing,4.0,752.130000,Bank Transfer,Delivered,3008.520000
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,Books,1.0,411.810000,Credit Card,Processing,411.810000
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2.0,413.130000,Cash on Delivery,Shipped,826.260000
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,Books,2.0,796.840000,Cash on Delivery,Returned,1593.680000
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4.0,464.828333,Cash on Delivery,Processing,1859.313333
17,117,Customer_117,ORD-72751,2/12/2025,Blender,Electronic,-2.0,10000.000000,Cash on Delivery,Processing,-20000.000000
18,118,Customer_118,ORD-96061,5/31/2025,Science,Books,5.0,247.820000,PayPal,Processing,1239.100000
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,Sports,4.0,438.190000,Cash on Delivery,Processing,1752.760000
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,Electronics,5.0,468.885333,Credit Card,Cancelled,2344.426667
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,Sports,4.0,523.010000,Credit Card,Delivered,2092.040000
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2.0,556.930000,PayPal,Shipped,1113.860000
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,Electronic,3.0,615.910000,Cash on Delivery,Cancelled,1847.730000
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5.0,532.278276,PayPal,Cancelled,2661.391379
25,125,Customer_125,ORD-23202,2/9/2025,Comics,Books,4.0,765.690000,PayPal,Shipped,3062.760000
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,Clothing,4.0,836.800000,Bank Transfer,Cancelled,3347.200000
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5.0,336.020000,Bank Transfer,Returned,1680.100000
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,Electronics,3.0,898.690000,Bank Transfer,Delivered,2696.070000
29,129,Customer_129,ORD-48863,6/22/2025,Science,Books,4.0,736.710000,Bank Transfer,Returned,2946.840000
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2.0,498.081333,Bank Transfer,Processing,996.162667
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,Home,5.0,616.630000,PayPal,Shipped,3083.150000
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,Electronics,1.0,266.700000,PayPal,Delivered,266.700000
33,133,Customer_133,ORD-68182,12/5/2024,Biography,Books,5.0,343.240000,Credit Card,Shipped,1716.200000
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5.0,591.530000,PayPal,Shipped,-2957.650000
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,Electronics,4.0,446.190000,Cash on Delivery,Cancelled,1784.760000
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,Books,1.0,696.710000,Credit Card,Delivered,696.710000
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,Home,3.0,-100.000000,Cash on Delivery,Delivered,-300.000000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,Home,1.0,531.060000,PayPal,Processing,531.060000
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,Electronics,2.0,681.380000,Credit Card,Cancelled,1362.760000
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,Books,4.0,588.980000,Credit Card,Returned,2355.920000
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,Books,3.0,546.040000,Cash on Delivery,Returned,1638.120000
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5.0,645.260000,Credit Card,Shipped,3226.300000
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,Clothing,5.0,826.770000,Bank Transfer,Cancelled,4133.850000
44,144,Customer_144,ORD-89452,1/27/2025,Football,Sports,5.0,849.070000,Bank Transfer,Processing,4245.350000
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,Electronics,2.0,860.990000,Bank Transfer,Returned,1721.980000
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,Electronic,2.0,705.420000,Bank Transfer,Processing,1410.840000
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4.0,596.150000,Cash on Delivery,Shipped,2384.600000
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,Sports,1.0,660.980000,Cash on Delivery,Returned,660.980000
49,149,Customer_149,ORD-95911,6/29/2025,Comics,Books,5.0,896.380000,Bank Transfer,Cancelled,4481.900000
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,Sports,1.0,206.190000,Credit Card,Returned,206.190000
51,151,Customer_151,ORD-56552,7/1/2025,Comics,Books,2.0,457.160000,PayPal,Processing,914.320000
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,Home,3.0,233.110000,PayPal,Returned,699.330000
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,Sports,4.0,278.900000,Cash on Delivery,Processing,1115.600000
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5.0,789.640000,Cash on Delivery,Cancelled,3948.200000
55,155,Customer_155,ORD-20182,5/1/2025,shoes,Clothing,1.0,40.950000,PayPal,Returned,40.950000
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2.0,560.540000,Bank Transfer,Shipped,1121.080000
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4.0,275.100000,Bank Transfer,Processing,1100.400000
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1.0,933.580000,Cash on Delivery,Shipped,933.580000
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3.0,163.160000,PayPal,Shipped,489.480000
60,160,Customer_160,ORD-96037,1/3/2025,Science,Books,5.0,242.520000,Cash on Delivery,Returned,1212.600000
61,161,Customer_161,ORD-27653,12/15/2024,Science,Books,4.0,209.320000,Bank Transfer,Shipped,837.280000
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2.0,155.760000,Credit Card,Returned,311.520000
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,Electronics,3.0,235.260000,Cash on Delivery,Shipped,705.780000
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,Sports,3.0,587.640000,Credit Card,Returned,1762.920000
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,Clothing,2.0,443.130000,Credit Card,Delivered,886.260000
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,Electronics,2.0,569.380000,Cash on Delivery,Shipped,1138.760000
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,Sports,3.0,593.930000,Cash on Delivery,Processing,1781.790000
68,168,Customer_168,ORD-53430,11/4/2025,Biography,Books,2.0,141.490000,PayPal,Cancelled,282.980000
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,Sports,1.0,582.130000,Credit Card,Returned,582.130000
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,Clothing,5.0,741.630000,Bank Transfer,Processing,3708.150000
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,Clothing,3.0,688.680000,PayPal,Processing,2066.040000
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2.0,942.760000,Bank Transfer,Returned,1885.520000
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,Home,5.0,351.890000,Credit Card,Shipped,1759.450000
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,Electronics,4.0,187.480000,Credit Card,Returned,749.920000
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1.0,111.360000,Credit Card,Processing,111.360000
76,176,Customer_176,ORD-95794,7/22/2025,Comics,Books,5.0,530.520000,Cash on Delivery,Shipped,2652.600000
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,Electronics,1.0,69.480000,Bank Transfer,Returned,69.480000
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,Sports,3.0,472.140000,PayPal,Returned,1416.420000
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,Sports,3.0,868.670000,PayPal,Delivered,2606.010000
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,Books,2.0,418.380000,Credit Card,Processing,836.760000
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,Books,1.0,266.480000,Cash on Delivery,Cancelled,266.480000
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,Books,4.0,538.350000,PayPal,Processing,2153.400000
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5.0,560.540000,Cash on Delivery,Returned,2802.700000
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,Books,4.0,101.190000,Bank Transfer,Processing,404.760000
85,185,Customer_185,ORD-57123,8/14/2025,Football,Sports,2.0,730.920000,Cash on Delivery,Cancelled,1461.840000
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1.0,365.340000,Bank Transfer,Delivered,365.340000
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,Electronics,3.0,882.960000,Bank Transfer,Returned,2648.880000
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5.0,504.050000,Cash on Delivery,Shipped,2520.250000
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,Home,1.0,814.680000,Cash on Delivery,Returned,814.680000
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1.0,920.370000,Bank Transfer,Processing,920.370000
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,Books,2.0,881.020000,Cash on Delivery,Returned,1762.040000
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,3.0,203.630000,Credit Card,Returned,610.890000
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,Books,3.0,522.020000,PayPal,Shipped,1566.060000
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5.0,944.540000,Cash on Delivery,Returned,4722.700000
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5.0,817.460000,Cash on Delivery,Returned,4087.300000
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,3.0,464.828333,PayPal,Delivered,1394.485000
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1.0,160.160000,PayPal,Cancelled,160.160000
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,Books,2.0,497.010000,Cash on Delivery,Shipped,994.020000
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5.0,372.280000,Credit Card,Shipped,1861.400000

In [146]:
df.duplicated().sum()

np.int64(3)

In [147]:
df[df.duplicated()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1.0,111.36,Credit Card,Processing,111.36
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5.0,645.26,Credit Card,Shipped,3226.30
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,Electronic,2.0,705.42,Bank Transfer,Processing,1410.84

## Quantity correction 
Converted negative values to positive values

In [148]:
incorrect_total = df[df["Total"] != (df["Quantity"] * df["Price"])]
print(incorrect_total)

Empty DataFrame
Columns: [ID, Customer_Name, Order_ID, Order_Date, Product, Category, Quantity, Price, Payment_Method, Status, Total]
Index: []

In [149]:
df[df["Quantity"]<0]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
17,117,Customer_117,ORD-72751,2/12/2025,Blender,Electronic,-2.0,10000.00,Cash on Delivery,Processing,-20000.00
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5.0,591.53,PayPal,Shipped,-2957.65

In [150]:
df["Quantity"] = df["Quantity"].abs()

## Fix wrong data types

In [151]:
df.dtypes

ID                  int64
Customer_Name      object
Order_ID           object
Order_Date         object
Product            object
Category           object
Quantity          float64
Price             float64
Payment_Method     object
Status             object
Total             float64
dtype: object

In [152]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"],format="mixed",errors="coerce")
df["Quantity"] = pd.to_numeric(df["Quantity"])
df["Price"] = pd.to_numeric(df["Price"])
df["Total"] = pd.to_numeric(df["Total"])

In [153]:
df.dtypes

ID                         int64
Customer_Name             object
Order_ID                  object
Order_Date        datetime64[ns]
Product                   object
Category                  object
Quantity                 float64
Price                    float64
Payment_Method            object
Status                    object
Total                    float64
dtype: object

In [155]:
df.to_csv("cleaned_ecommerce_sales_data.csv", index=False)
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3.0,38.000000,Cash on Delivery,Shipped,114.000000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2.0,468.885333,PayPal,Processing,937.770667
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1.0,389.050000,PayPal,Delivered,389.050000
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5.0,233.920000,PayPal,Processing,1169.600000
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1.0,552.510000,Cash on Delivery,Processing,552.510000
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3.0,122.060000,Cash on Delivery,Cancelled,366.180000
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,3.0,978.630000,Bank Transfer,Processing,2935.890000
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5.0,587.680000,PayPal,Returned,2938.400000
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1.0,600.290000,Cash on Delivery,Processing,600.290000
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5.0,168.340000,Credit Card,Shipped,841.700000
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5.0,498.081333,Cash on Delivery,Cancelled,2490.406667
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2.0,865.770000,Credit Card,Returned,1731.540000
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4.0,752.130000,Bank Transfer,Delivered,3008.520000
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1.0,411.810000,Credit Card,Processing,411.810000
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2.0,413.130000,Cash on Delivery,Shipped,826.260000
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2.0,796.840000,Cash on Delivery,Returned,1593.680000
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4.0,464.828333,Cash on Delivery,Processing,1859.313333
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronic,2.0,10000.000000,Cash on Delivery,Processing,-20000.000000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5.0,247.820000,PayPal,Processing,1239.100000
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4.0,438.190000,Cash on Delivery,Processing,1752.760000
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5.0,468.885333,Credit Card,Cancelled,2344.426667
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4.0,523.010000,Credit Card,Delivered,2092.040000
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2.0,556.930000,PayPal,Shipped,1113.860000
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronic,3.0,615.910000,Cash on Delivery,Cancelled,1847.730000
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5.0,532.278276,PayPal,Cancelled,2661.391379
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4.0,765.690000,PayPal,Shipped,3062.760000
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4.0,836.800000,Bank Transfer,Cancelled,3347.200000
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5.0,336.020000,Bank Transfer,Returned,1680.100000
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3.0,898.690000,Bank Transfer,Delivered,2696.070000
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4.0,736.710000,Bank Transfer,Returned,2946.840000
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2.0,498.081333,Bank Transfer,Processing,996.162667
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5.0,616.630000,PayPal,Shipped,3083.150000
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1.0,266.700000,PayPal,Delivered,266.700000
33,133,Customer_133,ORD-68182,2024-12-05,Biography,Books,5.0,343.240000,Credit Card,Shipped,1716.200000
34,134,Customer_134,ORD-16585,2025-10-04,T-shirt,Clothing,5.0,591.530000,PayPal,Shipped,-2957.650000
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4.0,446.190000,Cash on Delivery,Cancelled,1784.760000
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,Books,1.0,696.710000,Credit Card,Delivered,696.710000
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3.0,-100.000000,Cash on Delivery,Delivered,-300.000000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1.0,531.060000,PayPal,Processing,531.060000
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2.0,681.380000,Credit Card,Cancelled,1362.760000
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4.0,588.980000,Credit Card,Returned,2355.920000
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3.0,546.040000,Cash on Delivery,Returned,1638.120000
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5.0,645.260000,Credit Card,Shipped,3226.300000
43,143,Customer_143,ORD-14329,2025-07-11,T-shirt,Clothing,5.0,826.770000,Bank Transfer,Cancelled,4133.850000
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5.0,849.070000,Bank Transfer,Processing,4245.350000
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2.0,860.990000,Bank Transfer,Returned,1721.980000
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronic,2.0,705.420000,Bank Transfer,Processing,1410.840000
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4.0,596.150000,Cash on Delivery,Shipped,2384.600000
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1.0,660.980000,Cash on Delivery,Returned,660.980000
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5.0,896.380000,Bank Transfer,Cancelled,4481.900000
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1.0,206.190000,Credit Card,Returned,206.190000
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2.0,457.160000,PayPal,Processing,914.320000
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3.0,233.110000,PayPal,Returned,699.330000
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4.0,278.900000,Cash on Delivery,Processing,1115.600000
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5.0,789.640000,Cash on Delivery,Cancelled,3948.200000
55,155,Customer_155,ORD-20182,2025-05-01,shoes,Clothing,1.0,40.950000,PayPal,Returned,40.950000
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2.0,560.540000,Bank Transfer,Shipped,1121.080000
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4.0,275.100000,Bank Transfer,Processing,1100.400000
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1.0,933.580000,Cash on Delivery,Shipped,933.580000
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3.0,163.160000,PayPal,Shipped,489.480000
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5.0,242.520000,Cash on Delivery,Returned,1212.600000
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4.0,209.320000,Bank Transfer,Shipped,837.280000
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2.0,155.760000,Credit Card,Returned,311.520000
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3.0,235.260000,Cash on Delivery,Shipped,705.780000
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,3.0,587.640000,Credit Card,Returned,1762.920000
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2.0,443.130000,Credit Card,Delivered,886.260000
66,166,Customer_166,ORD-97756,2025-07-03,T-shirt,Electronics,2.0,569.380000,Cash on Delivery,Shipped,1138.760000
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,3.0,593.930000,Cash on Delivery,Processing,1781.790000
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2.0,141.490000,PayPal,Cancelled,282.980000
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1.0,582.130000,Credit Card,Returned,582.130000
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5.0,741.630000,Bank Transfer,Processing,3708.150000
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3.0,688.680000,PayPal,Processing,2066.040000
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2.0,942.760000,Bank Transfer,Returned,1885.520000
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5.0,351.890000,Credit Card,Shipped,1759.450000
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4.0,187.480000,Credit Card,Returned,749.920000
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1.0,111.360000,Credit Card,Processing,111.360000
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5.0,530.520000,Cash on Delivery,Shipped,2652.600000
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1.0,69.480000,Bank Transfer,Returned,69.480000
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3.0,472.140000,PayPal,Returned,1416.420000
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3.0,868.670000,PayPal,Delivered,2606.010000
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,Books,2.0,418.380000,Credit Card,Processing,836.760000
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,Books,1.0,266.480000,Cash on Delivery,Cancelled,266.480000
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,Books,4.0,538.350000,PayPal,Processing,2153.400000
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5.0,560.540000,Cash on Delivery,Returned,2802.700000
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,Books,4.0,101.190000,Bank Transfer,Processing,404.760000
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2.0,730.920000,Cash on Delivery,Cancelled,1461.840000
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1.0,365.340000,Bank Transfer,Delivered,365.340000
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3.0,882.960000,Bank Transfer,Returned,2648.880000
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5.0,504.050000,Cash on Delivery,Shipped,2520.250000
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1.0,814.680000,Cash on Delivery,Returned,814.680000
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1.0,920.370000,Bank Transfer,Processing,920.370000
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2.0,881.020000,Cash on Delivery,Returned,1762.040000
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,3.0,203.630000,Credit Card,Returned,610.890000
93,193,Customer_193,ORD-42475,2025-06-06,Basketball,Books,3.0,522.020000,PayPal,Shipped,1566.060000
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5.0,944.540000,Cash on Delivery,Returned,4722.700000
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5.0,817.460000,Cash on Delivery,Returned,4087.300000
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,3.0,464.828333,PayPal,Delivered,1394.485000
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1.0,160.160000,PayPal,Cancelled,160.160000
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Books,2.0,497.010000,Cash on Delivery,Shipped,994.020000
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5.0,372.280000,Credit Card,Shipped,1861.400000
100,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1.0,111.360000,Credit Card,Processing,111.360000
101,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5.0,645.260000,Credit Card,Shipped,3226.300000
102,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronic,2.0,705.420000,Bank Transfer,Processing,1410.840000